/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.CardLayout;

/**
 *
 * @author Stazzer
 */
public class Sims extends javax.swing.JFrame {

    /**
     * Creates new form Sims
     */
    CardLayout cl;
    
    public Sims() {
        initComponents();
        setSize(800, 600);
        buyCoins.setSize(400, 320);
        buyCoins.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jPanel2.setVisible(false);
        cl = (CardLayout)(jPanel2.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyCoins = new javax.swing.JDialog();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        startPlanningGame = new javax.swing.JPanel();
        startNewGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        loadGame = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gamePlaying = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar3 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        gamePlanning = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel17 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        jProgressBar8 = new javax.swing.JProgressBar();
        jProgressBar9 = new javax.swing.JProgressBar();
        jProgressBar10 = new javax.swing.JProgressBar();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jProgressBar11 = new javax.swing.JProgressBar();
        jProgressBar12 = new javax.swing.JProgressBar();
        jPanel11 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel87 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jLabel85 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel31 = new javax.swing.JPanel();
        shop = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jLabel62 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jLabel73 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();

        buyCoins.getContentPane().setLayout(null);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel74.setText("UCoins => Credits Tausch");
        buyCoins.getContentPane().add(jLabel74);
        jLabel74.setBounds(30, 20, 370, 60);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel75.setText("UCoins:");
        buyCoins.getContentPane().add(jLabel75);
        jLabel75.setBounds(200, 90, 80, 20);

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel76.setText("5 x");
        buyCoins.getContentPane().add(jLabel76);
        jLabel76.setBounds(270, 80, 80, 40);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel77.setText("Credits:");
        buyCoins.getContentPane().add(jLabel77);
        jLabel77.setBounds(50, 90, 70, 20);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel78.setText("600 x");
        buyCoins.getContentPane().add(jLabel78);
        jLabel78.setBounds(120, 80, 80, 40);

        jLabel79.setText("1 UCoin = 1000 Credits");
        buyCoins.getContentPane().add(jLabel79);
        jLabel79.setBounds(130, 120, 140, 30);

        jLabel80.setText("Wie viele Credits tauschen: ");
        buyCoins.getContentPane().add(jLabel80);
        jLabel80.setBounds(70, 160, 160, 30);

        jTextField1.setMinimumSize(new java.awt.Dimension(30, 20));
        buyCoins.getContentPane().add(jTextField1);
        jTextField1.setBounds(230, 160, 40, 30);

        jButton2.setText("Tauschen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buyCoins.getContentPane().add(jButton2);
        jButton2.setBounds(50, 240, 130, 23);

        jButton3.setText("Abbrechen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buyCoins.getContentPane().add(jButton3);
        jButton3.setBounds(210, 240, 130, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startPlanningGame.setMinimumSize(new java.awt.Dimension(800, 600));
        startPlanningGame.setName("");
        startPlanningGame.setPreferredSize(new java.awt.Dimension(800, 600));
        startPlanningGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startNewGame.setText("Neues Spiel");
        startNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameActionPerformed(evt);
            }
        });
        startPlanningGame.add(startNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SIMS Test Menü");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startPlanningGame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 330, 80));

        exit.setText("Beenden");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        startPlanningGame.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 160, 30));

        loadGame.setText("Spiel Laden");
        loadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameActionPerformed(evt);
            }
        });
        startPlanningGame.add(loadGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 160, 30));

        jButton6.setText("Statistik");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 160, 30));

        jButton7.setText("Profil");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 160, 30));

        jButton8.setText("Credits");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 160, 30));

        jButton13.setText("Abmelden");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 160, 30));

        jPanel1.add(startPlanningGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        jPanel2.setLayout(new java.awt.CardLayout());

        gamePlaying.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIMS Logo");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 150, 110);

        gamePlaying.add(jPanel3);
        jPanel3.setBounds(0, 0, 150, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Inventar");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 0, 120, 40);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(80, 160, 60, 60);

        jLabel18.setText("Studenten:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(20, 310, 80, 14);

        jLabel19.setText("4 / 40");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(90, 310, 50, 14);

        jLabel20.setText("Semester: ");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(20, 330, 80, 14);

        jLabel21.setText("3 / 6");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(90, 330, 60, 14);

        jLabel22.setText("3 UC");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(100, 80, 40, 14);

        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel16);
        jLabel16.setBounds(10, 60, 60, 60);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel17);
        jLabel17.setBounds(80, 60, 60, 60);

        jLabel23.setText("700 C");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(20, 80, 40, 14);

        jLabel24.setText("Red Bull");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(20, 170, 70, 14);

        jLabel25.setText("3 x");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(30, 190, 40, 14);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel15);
        jLabel15.setBounds(10, 160, 60, 60);

        gamePlaying.add(jPanel4);
        jPanel4.setBounds(0, 110, 150, 450);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel5.setText("Wissen");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 10, 70, 14);

        jLabel6.setText("Motivation");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 60, 80, 14);

        jLabel7.setText("Müdigkeit");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(100, 10, 80, 14);

        jLabel8.setText("Intelligenz");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(100, 60, 90, 14);
        jPanel5.add(jProgressBar1);
        jProgressBar1.setBounds(10, 30, 60, 14);
        jPanel5.add(jProgressBar2);
        jProgressBar2.setBounds(10, 80, 60, 14);
        jPanel5.add(jProgressBar3);
        jProgressBar3.setBounds(100, 80, 60, 14);
        jPanel5.add(jProgressBar4);
        jProgressBar4.setBounds(100, 30, 60, 14);

        jButton1.setText("Fenster");
        jPanel5.add(jButton1);
        jButton1.setBounds(200, 20, 120, 23);

        jButton4.setText("Gruppenarbeit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(200, 50, 120, 20);

        jButton5.setText("Pause");
        jPanel5.add(jButton5);
        jButton5.setBounds(200, 80, 120, 23);

        jLabel9.setText("Lärmpegel");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(350, 10, 80, 14);

        jLabel10.setText("Luftqualität");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(350, 60, 80, 14);
        jPanel5.add(jProgressBar5);
        jProgressBar5.setBounds(350, 30, 130, 14);
        jPanel5.add(jProgressBar6);
        jProgressBar6.setBounds(350, 80, 130, 14);

        gamePlaying.add(jPanel5);
        jPanel5.setBounds(150, 0, 500, 110);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jLabel4.setText("3 : 00 Min");
        jPanel6.add(jLabel4);
        jLabel4.setBounds(40, 40, 80, 14);

        jLabel3.setText("Verbleibende Zeit:");
        jPanel6.add(jLabel3);
        jLabel3.setBounds(20, -10, 110, 70);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Punkte:");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(10, 70, 70, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("700");
        jPanel6.add(jLabel14);
        jLabel14.setBounds(80, 60, 40, 40);

        gamePlaying.add(jPanel6);
        jPanel6.setBounds(650, 0, 130, 110);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gamePlaying.add(jPanel7);
        jPanel7.setBounds(150, 110, 630, 450);

        jPanel2.add(gamePlaying, "card2");

        gamePlanning.setName("card3");
        gamePlanning.setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("SIMS Logo");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        jPanel8.add(jLabel27);
        jLabel27.setBounds(0, 0, 150, 110);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel14.setLayout(null);

        jLabel47.setText("Studenten umsetzen");
        jPanel14.add(jLabel47);
        jLabel47.setBounds(20, 40, 160, 14);

        jLabel48.setText("Schritt 1:");
        jPanel14.add(jLabel48);
        jLabel48.setBounds(10, 10, 100, 14);

        jLabel52.setText("5 x");
        jPanel14.add(jLabel52);
        jLabel52.setBounds(60, 60, 50, 20);

        jPanel9.add(jPanel14);
        jPanel14.setBounds(0, 0, 150, 110);

        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(null);

        jLabel50.setText("Schritt 2:");
        jPanel15.add(jLabel50);
        jLabel50.setBounds(10, 10, 60, 20);

        jLabel51.setText("Dozent wechseln");
        jPanel15.add(jLabel51);
        jLabel51.setBounds(30, 50, 110, 14);

        jLabel49.setText("1 x");
        jPanel15.add(jLabel49);
        jLabel49.setBounds(60, 70, 50, 20);

        jPanel9.add(jPanel15);
        jPanel15.setBounds(0, 110, 150, 110);

        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel16.setLayout(null);

        jLabel53.setText("Schritt 3:");
        jPanel16.add(jLabel53);
        jLabel53.setBounds(10, 10, 80, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item Auswählen", "Spickzettel", "Item 3", "Item 4" }));
        jPanel16.add(jComboBox1);
        jComboBox1.setBounds(10, 50, 130, 20);

        jPanel9.add(jPanel16);
        jPanel16.setBounds(0, 220, 150, 110);

        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(null);
        jPanel9.add(jPanel17);
        jPanel17.setBounds(0, 330, 150, 120);

        jPanel8.add(jPanel9);
        jPanel9.setBounds(0, 110, 150, 450);

        gamePlanning.add(jPanel8);
        jPanel8.setBounds(0, 0, 150, 110);

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(null);

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel28.setText("Inventar");
        jPanel13.add(jLabel28);
        jLabel28.setBounds(30, 0, 120, 40);

        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(jLabel29);
        jLabel29.setBounds(80, 160, 60, 60);

        jLabel30.setText("Studenten:");
        jPanel13.add(jLabel30);
        jLabel30.setBounds(20, 310, 80, 14);

        jLabel31.setText("4 / 40");
        jPanel13.add(jLabel31);
        jLabel31.setBounds(90, 310, 50, 14);

        jLabel32.setText("Semester: ");
        jPanel13.add(jLabel32);
        jLabel32.setBounds(20, 330, 80, 14);

        jLabel33.setText("3 / 6");
        jPanel13.add(jLabel33);
        jLabel33.setBounds(90, 330, 60, 14);

        jLabel34.setText("3 UC");
        jPanel13.add(jLabel34);
        jLabel34.setBounds(100, 80, 40, 14);

        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(jLabel35);
        jLabel35.setBounds(10, 60, 60, 60);

        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(jLabel36);
        jLabel36.setBounds(80, 60, 60, 60);

        jLabel37.setText("700 C");
        jPanel13.add(jLabel37);
        jLabel37.setBounds(20, 80, 40, 14);

        jLabel38.setText("Red Bull");
        jPanel13.add(jLabel38);
        jLabel38.setBounds(20, 170, 70, 14);

        jLabel39.setText("3 x");
        jPanel13.add(jLabel39);
        jLabel39.setBounds(30, 190, 40, 14);

        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.add(jLabel40);
        jLabel40.setBounds(10, 160, 60, 60);

        jPanel10.add(jPanel13);
        jPanel13.setBounds(0, 110, 150, 450);

        jLabel41.setText("Wissen");
        jPanel10.add(jLabel41);
        jLabel41.setBounds(10, 10, 70, 14);

        jLabel42.setText("Motivation");
        jPanel10.add(jLabel42);
        jLabel42.setBounds(10, 60, 80, 14);

        jLabel43.setText("Müdigkeit");
        jPanel10.add(jLabel43);
        jLabel43.setBounds(100, 10, 80, 14);

        jLabel44.setText("Intelligenz");
        jPanel10.add(jLabel44);
        jLabel44.setBounds(100, 60, 90, 14);
        jPanel10.add(jProgressBar7);
        jProgressBar7.setBounds(10, 30, 60, 14);
        jPanel10.add(jProgressBar8);
        jProgressBar8.setBounds(10, 80, 60, 14);
        jPanel10.add(jProgressBar9);
        jProgressBar9.setBounds(100, 80, 60, 14);
        jPanel10.add(jProgressBar10);
        jProgressBar10.setBounds(100, 30, 60, 14);

        jButton9.setText("Fenster");
        jPanel10.add(jButton9);
        jButton9.setBounds(200, 20, 120, 23);

        jButton10.setText("Gruppenarbeit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10);
        jButton10.setBounds(200, 50, 120, 20);

        jButton11.setText("Pause");
        jPanel10.add(jButton11);
        jButton11.setBounds(200, 80, 120, 23);

        jLabel45.setText("Lärmpegel");
        jPanel10.add(jLabel45);
        jLabel45.setBounds(350, 10, 80, 14);

        jLabel46.setText("Luftqualität");
        jPanel10.add(jLabel46);
        jLabel46.setBounds(350, 60, 80, 14);
        jPanel10.add(jProgressBar11);
        jProgressBar11.setBounds(350, 30, 130, 14);
        jPanel10.add(jProgressBar12);
        jProgressBar12.setBounds(350, 80, 130, 14);

        gamePlanning.add(jPanel10);
        jPanel10.setBounds(150, 0, 500, 110);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(null);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("SHOP");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        jPanel11.add(jLabel26);
        jLabel26.setBounds(0, 0, 130, 110);

        gamePlanning.add(jPanel11);
        jPanel11.setBounds(650, 0, 130, 110);

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(null);
        gamePlanning.add(jPanel12);
        jPanel12.setBounds(150, 110, 630, 450);

        jPanel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel27.setLayout(null);

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel28.setLayout(null);

        jLabel87.setText("Schritt 1:");
        jPanel28.add(jLabel87);
        jLabel87.setBounds(10, 10, 70, 20);

        jLabel90.setText("Studenten umsetzen");
        jPanel28.add(jLabel90);
        jLabel90.setBounds(20, 40, 150, 20);

        jLabel92.setText("5 x");
        jPanel28.add(jLabel92);
        jLabel92.setBounds(60, 60, 60, 20);

        jPanel27.add(jPanel28);
        jPanel28.setBounds(0, 0, 150, 110);
        jPanel28.getAccessibleContext().setAccessibleDescription("");

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel29.setLayout(null);

        jLabel88.setText("Schritt 2:");
        jPanel29.add(jLabel88);
        jLabel88.setBounds(10, 10, 70, 20);

        jLabel89.setText("Dozenten tauschen");
        jPanel29.add(jLabel89);
        jLabel89.setBounds(20, 40, 110, 20);

        jLabel91.setText("1 x");
        jPanel29.add(jLabel91);
        jLabel91.setBounds(60, 60, 60, 20);

        jPanel27.add(jPanel29);
        jPanel29.setBounds(0, 110, 150, 110);

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.setLayout(null);

        jLabel85.setText("Schritt 3:");
        jPanel30.add(jLabel85);
        jLabel85.setBounds(10, 10, 70, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item auswählen", "Spicker" }));
        jPanel30.add(jComboBox2);
        jComboBox2.setBounds(10, 50, 130, 20);

        jPanel27.add(jPanel30);
        jPanel30.setBounds(0, 220, 150, 120);

        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel31.setLayout(null);
        jPanel27.add(jPanel31);
        jPanel31.setBounds(0, 340, 150, 110);

        gamePlanning.add(jPanel27);
        jPanel27.setBounds(0, 110, 150, 450);

        jPanel2.add(gamePlanning, "card3");

        shop.setLayout(null);

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("SIMS Logo");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel18.add(jLabel55);
        jLabel55.setBounds(0, 0, 150, 110);

        shop.add(jPanel18);
        jPanel18.setBounds(0, 0, 150, 110);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(null);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel56.setText("Inventar");
        jPanel19.add(jLabel56);
        jLabel56.setBounds(30, 0, 120, 40);

        jLabel57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel57);
        jLabel57.setBounds(80, 160, 60, 60);

        jLabel58.setText("Studenten:");
        jPanel19.add(jLabel58);
        jLabel58.setBounds(20, 310, 80, 14);

        jLabel59.setText("4 / 40");
        jPanel19.add(jLabel59);
        jLabel59.setBounds(90, 310, 50, 14);

        jLabel60.setText("Semester: ");
        jPanel19.add(jLabel60);
        jLabel60.setBounds(20, 330, 80, 14);

        jLabel61.setText("3 / 6");
        jPanel19.add(jLabel61);
        jLabel61.setBounds(90, 330, 60, 14);

        jLabel64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel64);
        jLabel64.setBounds(80, 60, 60, 60);

        jLabel66.setText("Red Bull");
        jPanel19.add(jLabel66);
        jLabel66.setBounds(20, 170, 70, 14);

        jLabel67.setText("3 x");
        jPanel19.add(jLabel67);
        jLabel67.setBounds(30, 190, 40, 14);

        jLabel68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(jLabel68);
        jLabel68.setBounds(10, 160, 60, 60);

        jLabel63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel63.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel19.add(jLabel63);
        jLabel63.setBounds(10, 60, 60, 60);

        shop.add(jPanel19);
        jPanel19.setBounds(0, 110, 150, 450);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(null);

        jLabel62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel62.setText("7");
        jPanel20.add(jLabel62);
        jLabel62.setBounds(90, 20, 80, 20);

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setText("700");
        jPanel20.add(jLabel65);
        jLabel65.setBounds(90, 60, 70, 17);

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("1500");
        jPanel20.add(jLabel69);
        jLabel69.setBounds(330, 20, 70, 17);

        jButton12.setText("UCoins Tauschen");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton12);
        jButton12.setBounds(260, 60, 130, 23);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("UCoins:");
        jPanel20.add(jLabel70);
        jLabel70.setBounds(20, 20, 80, 20);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Credits:");
        jPanel20.add(jLabel71);
        jLabel71.setBounds(20, 60, 70, 17);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("Punkte:");
        jPanel20.add(jLabel72);
        jLabel72.setBounds(260, 20, 70, 17);

        shop.add(jPanel20);
        jPanel20.setBounds(150, 0, 500, 110);

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(null);

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("SPIEL");
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel54);
        jLabel54.setBounds(0, 0, 130, 110);

        shop.add(jPanel21);
        jPanel21.setBounds(650, 0, 130, 110);

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(null);

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(null);

        jLabel84.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel84.setText("Verfügbar ab Semester 4");
        jPanel23.add(jLabel84);
        jLabel84.setBounds(0, 100, 230, 50);

        jLabel86.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel86.setForeground(new java.awt.Color(204, 51, 0));
        jLabel86.setText("GESPERRT");
        jPanel23.add(jLabel86);
        jLabel86.setBounds(30, 10, 230, 110);

        jPanel22.add(jPanel23);
        jPanel23.setBounds(340, 250, 200, 180);

        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setLayout(null);
        jPanel22.add(jPanel24);
        jPanel24.setBounds(340, 40, 200, 180);

        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel25.setLayout(null);

        jLabel82.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel82.setText("Red Bull");
        jPanel25.add(jLabel82);
        jLabel82.setBounds(60, 110, 120, 30);

        jLabel83.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel83.setText("100 Credits");
        jPanel25.add(jLabel83);
        jLabel83.setBounds(50, 130, 130, 50);

        jPanel22.add(jPanel25);
        jPanel25.setBounds(70, 40, 200, 180);

        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel26.setLayout(null);

        jLabel73.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel73.setText("Spicker");
        jPanel26.add(jLabel73);
        jLabel73.setBounds(60, 110, 120, 30);

        jLabel81.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel81.setText("5 UCoins");
        jPanel26.add(jLabel81);
        jLabel81.setBounds(50, 130, 130, 50);

        jPanel22.add(jPanel26);
        jPanel26.setBounds(70, 250, 200, 180);

        shop.add(jPanel22);
        jPanel22.setBounds(150, 110, 630, 450);

        jPanel2.add(shop, "card4");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void startNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameActionPerformed
        // TODO add your handling code here:
        if(jPanel2.isVisible() == false){
            jPanel2.setVisible(true);
        }    
        cl.show(jPanel2, "card2");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_startNewGameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void loadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameActionPerformed
        // TODO add your handling code here:
        if(jPanel2.isVisible() == false){
            jPanel2.setVisible(true);
        }    
        cl.show(jPanel2, "card3");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_loadGameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        buyCoins.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
        // TODO add your handling code here:
        cl.show(jPanel2, "card4");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        // TODO add your handling code here:
        cl.show(jPanel2, "card3");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        buyCoins.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sims().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog buyCoins;
    private javax.swing.JButton exit;
    private javax.swing.JPanel gamePlanning;
    private javax.swing.JPanel gamePlaying;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar11;
    private javax.swing.JProgressBar jProgressBar12;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JProgressBar jProgressBar9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loadGame;
    private javax.swing.JPanel shop;
    private javax.swing.JButton startNewGame;
    private javax.swing.JPanel startPlanningGame;
    // End of variables declaration//GEN-END:variables
}
