/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Stazzer
 */
public class Sims_1 extends javax.swing.JFrame {

    /**
     * Creates new form Sims
     */
    public CardLayout cl;
    public Game game;
    
    public Sims_1() {
        initComponents();
        setSize(1000, 700);
        buyCoins.setSize(400, 320);
        buyCoins.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jPanel2.setVisible(false);
        cl = (CardLayout)(jPanel2.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyCoins = new javax.swing.JDialog();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        startPlanningGame = new javax.swing.JPanel();
        startNewGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        loadGame = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gamePlanning = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLab_Logo = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jProgB_Müdigkeit = new javax.swing.JProgressBar();
        jProgB_Motivation = new javax.swing.JProgressBar();
        jProgB_Wissen = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        Shop = new javax.swing.JPanel();
        enterShop = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        Navi = new javax.swing.JPanel();
        jPan_StudSwitch = new javax.swing.JPanel();
        jLab_StudSwitch = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLab_StudCounter = new javax.swing.JLabel();
        jBut_BackG = new javax.swing.JButton();
        jPan_DozSwitch = new javax.swing.JPanel();
        jLab_DozSwitch = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLab_DozCounter = new javax.swing.JLabel();
        jBut_BackG2 = new javax.swing.JButton();
        jPan_ItemSelect = new javax.swing.JPanel();
        jComboB_Items = new javax.swing.JComboBox();
        jBut_ComboB_useItem = new javax.swing.JButton();
        jPan_ItemStorage = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLab_Redbull = new javax.swing.JLabel();
        jLab_Duplo = new javax.swing.JLabel();
        jLab_OMNI = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jBut_Play = new javax.swing.JButton();
        StudField = new javax.swing.JPanel();
        jBut_Dozent = new javax.swing.JButton();
        jBut_1 = new javax.swing.JButton();
        jBut_2 = new javax.swing.JButton();
        jBut_3 = new javax.swing.JButton();
        jBut_4 = new javax.swing.JButton();
        jBut_5 = new javax.swing.JButton();
        jBut_6 = new javax.swing.JButton();
        jBut_7 = new javax.swing.JButton();
        jBut_8 = new javax.swing.JButton();
        jBut_9 = new javax.swing.JButton();
        jBut_10 = new javax.swing.JButton();
        jBut_11 = new javax.swing.JButton();
        jBut_12 = new javax.swing.JButton();
        jBut_13 = new javax.swing.JButton();
        jBut_14 = new javax.swing.JButton();
        jBut_15 = new javax.swing.JButton();
        jBut_16 = new javax.swing.JButton();
        jBut_17 = new javax.swing.JButton();
        jBut_18 = new javax.swing.JButton();
        jBut_19 = new javax.swing.JButton();
        jBut_20 = new javax.swing.JButton();
        jBut_21 = new javax.swing.JButton();
        jBut_22 = new javax.swing.JButton();
        jBut_23 = new javax.swing.JButton();
        jBut_24 = new javax.swing.JButton();
        jBut_25 = new javax.swing.JButton();
        jBut_26 = new javax.swing.JButton();
        jBut_27 = new javax.swing.JButton();
        jBut_28 = new javax.swing.JButton();
        jBut_29 = new javax.swing.JButton();
        jBut_30 = new javax.swing.JButton();
        shop = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        label_item3 = new javax.swing.JLabel();
        label_item1 = new javax.swing.JLabel();
        label_item2 = new javax.swing.JLabel();
        label_item1Name = new javax.swing.JLabel();
        label_item1Amount = new javax.swing.JLabel();
        label_item2Name = new javax.swing.JLabel();
        label_item2Amount = new javax.swing.JLabel();
        label_item3Name = new javax.swing.JLabel();
        label_item3Amount = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        ucoinsShop = new javax.swing.JLabel();
        creditsShop = new javax.swing.JLabel();
        punkteShop = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        label_omniName = new javax.swing.JLabel();
        label_omniLocked = new javax.swing.JLabel();
        label_omniAmount = new javax.swing.JLabel();
        panel_duplo = new javax.swing.JPanel();
        label_duploName = new javax.swing.JLabel();
        label_duploAmount = new javax.swing.JLabel();
        label_redDuplolLocked = new javax.swing.JLabel();
        panel_redBull = new javax.swing.JPanel();
        label_redBullName = new javax.swing.JLabel();
        label_redBullAmount = new javax.swing.JLabel();
        label_redBullLocked = new javax.swing.JLabel();
        panel_cheatSheet = new javax.swing.JPanel();
        label_cheatSheetName = new javax.swing.JLabel();
        label_cheatSheetLocked = new javax.swing.JLabel();
        label_cheatSheetAmount = new javax.swing.JLabel();
        gamePlaying = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        label_timer = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        buyCoins.getContentPane().setLayout(null);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel74.setText("UCoins => Credits Tausch");
        buyCoins.getContentPane().add(jLabel74);
        jLabel74.setBounds(30, 20, 370, 60);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel75.setText("UCoins:");
        buyCoins.getContentPane().add(jLabel75);
        jLabel75.setBounds(230, 110, 80, 20);

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel76.setText("5 x");
        buyCoins.getContentPane().add(jLabel76);
        jLabel76.setBounds(300, 100, 80, 40);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel77.setText("Credits:");
        buyCoins.getContentPane().add(jLabel77);
        jLabel77.setBounds(50, 110, 70, 20);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel78.setText("600 x");
        buyCoins.getContentPane().add(jLabel78);
        jLabel78.setBounds(120, 100, 80, 40);

        jLabel79.setText("1 UCoin = 1000 Credits");
        buyCoins.getContentPane().add(jLabel79);
        jLabel79.setBounds(140, 150, 140, 30);

        jTextField1.setMinimumSize(new java.awt.Dimension(30, 20));
        buyCoins.getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 150, 40, 30);

        jButton2.setText("Tauschen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buyCoins.getContentPane().add(jButton2);
        jButton2.setBounds(50, 220, 130, 23);

        jButton3.setText("Abbrechen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buyCoins.getContentPane().add(jButton3);
        jButton3.setBounds(210, 220, 130, 23);

        jTextField2.setMinimumSize(new java.awt.Dimension(30, 20));
        buyCoins.getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 150, 40, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 786));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startPlanningGame.setMinimumSize(new java.awt.Dimension(800, 600));
        startPlanningGame.setName("");
        startPlanningGame.setPreferredSize(new java.awt.Dimension(800, 600));
        startPlanningGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startNewGame.setText("Neues Spiel");
        startNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameActionPerformed(evt);
            }
        });
        startPlanningGame.add(startNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SIMS Test Menü");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startPlanningGame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 330, 80));

        exit.setText("Beenden");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        startPlanningGame.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 160, 30));

        loadGame.setText("Spiel Laden");
        loadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameActionPerformed(evt);
            }
        });
        startPlanningGame.add(loadGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 160, 30));

        jButton6.setText("Credits");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 160, 30));

        jButton7.setText("Profil");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 160, 30));

        jButton8.setText("Abmelden");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 160, 30));

        jButton13.setText("Statistik");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 160, 30));

        jPanel1.add(startPlanningGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        jPanel2.setLayout(new java.awt.CardLayout());

        gamePlanning.setName("card3");
        gamePlanning.setLayout(null);

        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Logo.setLayout(null);

        jLab_Logo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLab_Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLab_Logo.setText("SIMS Logo");
        jLab_Logo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLab_LogoMouseClicked(evt);
            }
        });
        Logo.add(jLab_Logo);
        jLab_Logo.setBounds(0, 0, 150, 110);

        gamePlanning.add(Logo);
        Logo.setBounds(0, 0, 150, 110);

        Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Header.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Wissen:");
        Header.add(jLabel41);
        jLabel41.setBounds(10, 20, 70, 20);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Motivation:");
        Header.add(jLabel42);
        jLabel42.setBounds(10, 40, 80, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Müdigkeit:");
        Header.add(jLabel43);
        jLabel43.setBounds(10, 80, 90, 20);
        Header.add(jProgB_Müdigkeit);
        jProgB_Müdigkeit.setBounds(90, 80, 260, 20);
        Header.add(jProgB_Motivation);
        jProgB_Motivation.setBounds(90, 50, 260, 20);
        Header.add(jProgB_Wissen);
        jProgB_Wissen.setBounds(90, 20, 260, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("PLANUNGSPHASE");
        Header.add(jLabel3);
        jLabel3.setBounds(360, 10, 340, 90);

        gamePlanning.add(Header);
        Header.setBounds(150, 0, 700, 110);

        Shop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Shop.setLayout(null);

        enterShop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enterShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterShop.setText("SHOP");
        enterShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterShopMouseClicked(evt);
            }
        });
        Shop.add(enterShop);
        enterShop.setBounds(0, 0, 130, 110);

        jButton9.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jButton9.setText("SHOP");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        Shop.add(jButton9);
        jButton9.setBounds(5, 5, 120, 100);

        gamePlanning.add(Shop);
        Shop.setBounds(850, 0, 130, 110);

        Navi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Navi.setLayout(null);

        jPan_StudSwitch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPan_StudSwitch.setLayout(null);
        jPan_StudSwitch.add(jLab_StudSwitch);
        jLab_StudSwitch.setBounds(0, 0, 150, 110);

        jLabel4.setText("umsetzen");
        jPan_StudSwitch.add(jLabel4);
        jLabel4.setBounds(40, 40, 70, 14);

        jLabel90.setText("Studenten");
        jPan_StudSwitch.add(jLabel90);
        jLabel90.setBounds(40, 20, 70, 20);

        jLab_StudCounter.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLab_StudCounter.setText("5x");
        jPan_StudSwitch.add(jLab_StudCounter);
        jLab_StudCounter.setBounds(60, 60, 30, 24);

        jBut_BackG.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jBut_BackG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_BackGActionPerformed(evt);
            }
        });
        jPan_StudSwitch.add(jBut_BackG);
        jBut_BackG.setBounds(10, 10, 130, 90);

        Navi.add(jPan_StudSwitch);
        jPan_StudSwitch.setBounds(0, 0, 150, 110);
        jPan_StudSwitch.getAccessibleContext().setAccessibleDescription("");

        jPan_DozSwitch.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPan_DozSwitch.setLayout(null);
        jPan_DozSwitch.add(jLab_DozSwitch);
        jLab_DozSwitch.setBounds(0, 0, 150, 110);

        jLabel91.setText("Dozenten");
        jPan_DozSwitch.add(jLabel91);
        jLabel91.setBounds(40, 20, 70, 20);

        jLabel27.setText("tauschen");
        jPan_DozSwitch.add(jLabel27);
        jLabel27.setBounds(40, 40, 60, 20);

        jLab_DozCounter.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLab_DozCounter.setText("1x");
        jPan_DozSwitch.add(jLab_DozCounter);
        jLab_DozCounter.setBounds(60, 60, 30, 30);

        jBut_BackG2.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jBut_BackG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_BackG2ActionPerformed(evt);
            }
        });
        jPan_DozSwitch.add(jBut_BackG2);
        jBut_BackG2.setBounds(10, 10, 130, 90);

        Navi.add(jPan_DozSwitch);
        jPan_DozSwitch.setBounds(0, 110, 150, 110);

        jPan_ItemSelect.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPan_ItemSelect.setLayout(null);

        jComboB_Items.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "wähle Item", "Spicker" }));
        jPan_ItemSelect.add(jComboB_Items);
        jComboB_Items.setBounds(10, 20, 130, 30);

        jBut_ComboB_useItem.setText("Benutzen");
        jPan_ItemSelect.add(jBut_ComboB_useItem);
        jBut_ComboB_useItem.setBounds(20, 60, 77, 23);

        Navi.add(jPan_ItemSelect);
        jPan_ItemSelect.setBounds(0, 220, 150, 110);

        jPan_ItemStorage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPan_ItemStorage.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel8.setText("Item-Vorräte");
        jPan_ItemStorage.add(jLabel8);
        jLabel8.setBounds(10, 10, 120, 20);

        jLab_Redbull.setText("Redbull: 5");
        jPan_ItemStorage.add(jLab_Redbull);
        jLab_Redbull.setBounds(10, 40, 90, 14);

        jLab_Duplo.setText("Duplo: 3");
        jPan_ItemStorage.add(jLab_Duplo);
        jLab_Duplo.setBounds(10, 60, 90, 14);

        jLab_OMNI.setText("OMNI Sense Buch: 1");
        jPan_ItemStorage.add(jLab_OMNI);
        jLab_OMNI.setBounds(10, 80, 140, 14);

        Navi.add(jPan_ItemStorage);
        jPan_ItemStorage.setBounds(0, 330, 150, 110);

        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel32.setLayout(null);

        jBut_Play.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jBut_Play.setText("SPIELEN");
        jBut_Play.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_PlayActionPerformed(evt);
            }
        });
        jPanel32.add(jBut_Play);
        jBut_Play.setBounds(10, 10, 130, 90);

        Navi.add(jPanel32);
        jPanel32.setBounds(0, 440, 150, 110);

        gamePlanning.add(Navi);
        Navi.setBounds(0, 110, 150, 550);

        StudField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StudField.setLayout(null);

        jBut_Dozent.setText("Dozent");
        StudField.add(jBut_Dozent);
        jBut_Dozent.setBounds(340, 10, 110, 50);

        jBut_1.setText("Platz_1");
        StudField.add(jBut_1);
        jBut_1.setBounds(60, 120, 110, 50);

        jBut_2.setText("Platz_2");
        StudField.add(jBut_2);
        jBut_2.setBounds(210, 120, 110, 50);

        jBut_3.setText("Platz_3");
        StudField.add(jBut_3);
        jBut_3.setBounds(360, 120, 110, 50);

        jBut_4.setText("Platz_4");
        StudField.add(jBut_4);
        jBut_4.setBounds(510, 120, 110, 50);

        jBut_5.setText("Platz_5");
        StudField.add(jBut_5);
        jBut_5.setBounds(660, 120, 110, 50);

        jBut_6.setText("Platz_6");
        StudField.add(jBut_6);
        jBut_6.setBounds(60, 190, 110, 50);

        jBut_7.setText("Platz_7");
        StudField.add(jBut_7);
        jBut_7.setBounds(210, 190, 110, 50);

        jBut_8.setText("Platz_8");
        StudField.add(jBut_8);
        jBut_8.setBounds(360, 190, 110, 50);

        jBut_9.setText("Platz_9");
        StudField.add(jBut_9);
        jBut_9.setBounds(510, 190, 110, 50);

        jBut_10.setText("Platz_10");
        StudField.add(jBut_10);
        jBut_10.setBounds(660, 190, 110, 50);

        jBut_11.setText("Platz_11");
        StudField.add(jBut_11);
        jBut_11.setBounds(60, 260, 110, 50);

        jBut_12.setText("Platz_12");
        StudField.add(jBut_12);
        jBut_12.setBounds(210, 260, 110, 50);

        jBut_13.setText("Platz_13");
        StudField.add(jBut_13);
        jBut_13.setBounds(360, 260, 110, 50);

        jBut_14.setText("Platz_14");
        StudField.add(jBut_14);
        jBut_14.setBounds(510, 260, 110, 50);

        jBut_15.setText("Platz_15");
        StudField.add(jBut_15);
        jBut_15.setBounds(660, 260, 110, 50);

        jBut_16.setText("Platz_16");
        StudField.add(jBut_16);
        jBut_16.setBounds(60, 330, 110, 50);

        jBut_17.setText("Platz_17");
        jBut_17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBut_17ActionPerformed(evt);
            }
        });
        StudField.add(jBut_17);
        jBut_17.setBounds(210, 330, 110, 50);

        jBut_18.setText("Platz_18");
        StudField.add(jBut_18);
        jBut_18.setBounds(360, 330, 110, 50);

        jBut_19.setText("Platz_19");
        StudField.add(jBut_19);
        jBut_19.setBounds(510, 330, 110, 50);

        jBut_20.setText("Platz_20");
        StudField.add(jBut_20);
        jBut_20.setBounds(660, 330, 110, 50);

        jBut_21.setText("Platz_21");
        StudField.add(jBut_21);
        jBut_21.setBounds(60, 400, 110, 50);

        jBut_22.setText("Platz_22");
        StudField.add(jBut_22);
        jBut_22.setBounds(210, 400, 110, 50);

        jBut_23.setText("Platz_23");
        StudField.add(jBut_23);
        jBut_23.setBounds(360, 400, 110, 50);

        jBut_24.setText("Platz_24");
        StudField.add(jBut_24);
        jBut_24.setBounds(510, 400, 110, 50);

        jBut_25.setText("Platz_25");
        StudField.add(jBut_25);
        jBut_25.setBounds(660, 400, 110, 50);

        jBut_26.setText("Platz_26");
        StudField.add(jBut_26);
        jBut_26.setBounds(60, 470, 110, 50);

        jBut_27.setText("Platz_27");
        jBut_27.setToolTipText("");
        StudField.add(jBut_27);
        jBut_27.setBounds(210, 470, 110, 50);

        jBut_28.setText("Platz_28");
        StudField.add(jBut_28);
        jBut_28.setBounds(360, 470, 110, 50);

        jBut_29.setText("Platz_29");
        StudField.add(jBut_29);
        jBut_29.setBounds(510, 470, 110, 50);

        jBut_30.setText("Platz_30");
        StudField.add(jBut_30);
        jBut_30.setBounds(660, 470, 110, 50);

        gamePlanning.add(StudField);
        StudField.setBounds(150, 110, 830, 550);

        jPanel2.add(gamePlanning, "card3");

        shop.setLayout(null);

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("SIMS Logo");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel18.add(jLabel55);
        jLabel55.setBounds(0, 0, 150, 110);

        shop.add(jPanel18);
        jPanel18.setBounds(0, 0, 150, 110);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(null);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel56.setText("Inventar");
        jPanel19.add(jLabel56);
        jLabel56.setBounds(30, 0, 120, 40);

        jLabel58.setText("Studenten:");
        jPanel19.add(jLabel58);
        jLabel58.setBounds(10, 420, 80, 14);

        jLabel59.setText("4 / 40");
        jPanel19.add(jLabel59);
        jLabel59.setBounds(80, 420, 50, 14);

        jLabel60.setText("Semester: ");
        jPanel19.add(jLabel60);
        jLabel60.setBounds(10, 440, 80, 14);

        jLabel61.setText("3 / 6");
        jPanel19.add(jLabel61);
        jLabel61.setBounds(80, 440, 60, 14);

        label_item3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(label_item3);
        label_item3.setBounds(30, 250, 90, 80);

        label_item1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(label_item1);
        label_item1.setBounds(30, 50, 90, 80);

        label_item2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_item2.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel19.add(label_item2);
        label_item2.setBounds(30, 150, 90, 80);

        label_item1Name.setText("jLabel4");
        jPanel19.add(label_item1Name);
        label_item1Name.setBounds(60, 80, 34, 14);

        label_item1Amount.setText("jLabel4");
        jPanel19.add(label_item1Amount);
        label_item1Amount.setBounds(60, 100, 34, 14);

        label_item2Name.setText("jLabel4");
        jPanel19.add(label_item2Name);
        label_item2Name.setBounds(60, 190, 34, 14);

        label_item2Amount.setText("jLabel4");
        jPanel19.add(label_item2Amount);
        label_item2Amount.setBounds(60, 210, 34, 14);

        label_item3Name.setText("jLabel4");
        jPanel19.add(label_item3Name);
        label_item3Name.setBounds(60, 280, 34, 14);

        label_item3Amount.setText("jLabel26");
        jPanel19.add(label_item3Amount);
        label_item3Amount.setBounds(60, 300, 40, 14);

        shop.add(jPanel19);
        jPanel19.setBounds(0, 110, 150, 550);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(null);

        ucoinsShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ucoinsShop.setText("0");
        jPanel20.add(ucoinsShop);
        ucoinsShop.setBounds(80, 10, 80, 20);

        creditsShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        creditsShop.setText("0");
        jPanel20.add(creditsShop);
        creditsShop.setBounds(80, 40, 70, 17);

        punkteShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        punkteShop.setText("0");
        jPanel20.add(punkteShop);
        punkteShop.setBounds(80, 70, 70, 17);

        jButton12.setText("UCoins Tauschen");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton12);
        jButton12.setBounds(230, 10, 160, 90);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("UCoins:");
        jPanel20.add(jLabel70);
        jLabel70.setBounds(10, 10, 80, 20);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Credits:");
        jPanel20.add(jLabel71);
        jLabel71.setBounds(10, 40, 70, 17);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("Punkte:");
        jPanel20.add(jLabel72);
        jLabel72.setBounds(10, 70, 70, 17);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel85.setText("SHOP");
        jPanel20.add(jLabel85);
        jLabel85.setBounds(470, 0, 210, 110);

        shop.add(jPanel20);
        jPanel20.setBounds(150, 0, 700, 110);

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(null);

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("SPIEL");
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel54);
        jLabel54.setBounds(0, 0, 130, 110);

        shop.add(jPanel21);
        jPanel21.setBounds(850, 0, 130, 110);

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(null);

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(null);

        label_omniName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_omniName.setText("Verfügbar ab Semester 4");
        jPanel23.add(label_omniName);
        label_omniName.setBounds(20, 120, 230, 50);

        label_omniLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_omniLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_omniLocked.setText("GESPERRT");
        jPanel23.add(label_omniLocked);
        label_omniLocked.setBounds(50, 20, 230, 110);

        label_omniAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_omniAmount.setText("5 UCoins");
        jPanel23.add(label_omniAmount);
        label_omniAmount.setBounds(80, 150, 130, 50);

        jPanel22.add(jPanel23);
        jPanel23.setBounds(510, 290, 230, 220);

        panel_duplo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_duplo.setLayout(null);

        label_duploName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_duploName.setText("Duplo");
        panel_duplo.add(label_duploName);
        label_duploName.setBounds(90, 110, 120, 30);

        label_duploAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_duploAmount.setText("100 Credits");
        panel_duplo.add(label_duploAmount);
        label_duploAmount.setBounds(70, 130, 130, 50);

        label_redDuplolLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_redDuplolLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_redDuplolLocked.setText("GESPERRT");
        panel_duplo.add(label_redDuplolLocked);
        label_redDuplolLocked.setBounds(50, 10, 230, 110);

        jPanel22.add(panel_duplo);
        panel_duplo.setBounds(510, 40, 230, 220);

        panel_redBull.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_redBull.setName("panel_redBull");
        panel_redBull.setLayout(null);

        label_redBullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_redBullName.setText("Red Bull");
        panel_redBull.add(label_redBullName);
        label_redBullName.setBounds(80, 110, 120, 30);

        label_redBullAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_redBullAmount.setText("100 Credits");
        panel_redBull.add(label_redBullAmount);
        label_redBullAmount.setBounds(70, 130, 130, 50);

        label_redBullLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_redBullLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_redBullLocked.setText("GESPERRT");
        panel_redBull.add(label_redBullLocked);
        label_redBullLocked.setBounds(50, 10, 230, 110);

        jPanel22.add(panel_redBull);
        panel_redBull.setBounds(100, 40, 230, 220);

        panel_cheatSheet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cheatSheet.setLayout(null);

        label_cheatSheetName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_cheatSheetName.setText("Spicker");
        panel_cheatSheet.add(label_cheatSheetName);
        label_cheatSheetName.setBounds(90, 110, 120, 30);

        label_cheatSheetLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_cheatSheetLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_cheatSheetLocked.setText("GESPERRT");
        panel_cheatSheet.add(label_cheatSheetLocked);
        label_cheatSheetLocked.setBounds(50, 10, 230, 110);

        label_cheatSheetAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_cheatSheetAmount.setText("5 UCoins");
        panel_cheatSheet.add(label_cheatSheetAmount);
        label_cheatSheetAmount.setBounds(80, 130, 130, 50);

        jPanel22.add(panel_cheatSheet);
        panel_cheatSheet.setBounds(100, 300, 230, 220);

        shop.add(jPanel22);
        jPanel22.setBounds(150, 110, 830, 550);

        jPanel2.add(shop, "card4");

        gamePlaying.setMinimumSize(new java.awt.Dimension(1024, 768));
        gamePlaying.setPreferredSize(new java.awt.Dimension(1024, 768));
        gamePlaying.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIMS Logo");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 150, 110);

        gamePlaying.add(jPanel3);
        jPanel3.setBounds(0, 0, 150, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Inventar");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 0, 120, 40);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(30, 250, 90, 80);

        jLabel18.setText("Studenten:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 420, 80, 14);

        jLabel19.setText("4 / 40");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(80, 420, 50, 14);

        jLabel20.setText("Semester: ");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(10, 440, 80, 14);

        jLabel21.setText("3 / 6");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(80, 440, 60, 14);

        jLabel22.setText("UCoins: 300");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(80, 350, 80, 14);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel17);
        jLabel17.setBounds(30, 150, 90, 80);

        jLabel23.setText("Credis: 700");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 350, 70, 14);

        jLabel24.setText("Red Bull");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(50, 160, 90, 30);

        jLabel25.setText("3 x");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(60, 190, 40, 14);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 50, 90, 80);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Punkte:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 480, 70, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("700");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(90, 470, 40, 40);

        gamePlaying.add(jPanel4);
        jPanel4.setBounds(0, 110, 150, 550);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Wissen:");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 10, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Motivation:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 30, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Müdigkeit:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 80, 80, 20);
        jPanel5.add(jProgressBar1);
        jProgressBar1.setBounds(80, 10, 260, 20);
        jPanel5.add(jProgressBar2);
        jProgressBar2.setBounds(80, 40, 260, 20);
        jPanel5.add(jProgressBar4);
        jProgressBar4.setBounds(80, 80, 260, 20);

        jButton1.setText("Fenster : AUF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(350, 10, 120, 23);

        jButton4.setText("Gruppenarbeit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(350, 40, 120, 23);

        jButton5.setText("Pause");
        jPanel5.add(jButton5);
        jButton5.setBounds(350, 80, 120, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Lärmpegel:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(480, 10, 80, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Luftqualität:");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(480, 34, 80, 30);
        jPanel5.add(jProgressBar5);
        jProgressBar5.setBounds(560, 10, 130, 20);
        jPanel5.add(jProgressBar6);
        jProgressBar6.setBounds(560, 40, 130, 20);

        gamePlaying.add(jPanel5);
        jPanel5.setBounds(150, 0, 700, 110);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        label_timer.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        label_timer.setText("--:--");
        jPanel6.add(label_timer);
        label_timer.setBounds(10, 10, 140, 90);

        gamePlaying.add(jPanel6);
        jPanel6.setBounds(850, 0, 130, 110);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gamePlaying.add(jPanel7);
        jPanel7.setBounds(150, 110, 830, 550);

        jPanel2.add(gamePlaying, "card2");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void startNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameActionPerformed
        // TODO add your handling code here:
        if(jPanel2.isVisible() == false){
            jPanel2.setVisible(true);
        }    
        cl.show(jPanel2, "card2");
        startPlanningGame.setVisible(false);
        ActivityPhase phase = new ActivityPhase(label_timer); // added by Jörg
    }//GEN-LAST:event_startNewGameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void loadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameActionPerformed
        // TODO add your handling code here:
        if(jPanel2.isVisible() == false){
            jPanel2.setVisible(true);
        }    
        cl.show(jPanel2, "card3");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_loadGameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        buyCoins.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLab_LogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLab_LogoMouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLab_LogoMouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        // TODO add your handling code here:
        cl.show(jPanel2, "card3");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        buyCoins.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String test = jButton1.getText();
       if(test.equals("Fenster : AUF")){
           jButton1.setText("Fenster : ZU");
       }
       if(test.equals("Fenster : ZU")){
           jButton1.setText("Fenster : AUF");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBut_BackGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_BackGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_BackGActionPerformed

    private void jBut_BackG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_BackG2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_BackG2ActionPerformed

    private void jBut_PlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_PlayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_PlayActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton9ActionPerformed

    private void enterShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterShopMouseClicked
        // TODO add your handling code here:
        cl.show(jPanel2, "card4");
        startPlanningGame.setVisible(false);
        OpenShop labels = new OpenShop();
        labels.changeLabels(creditsShop, punkteShop, ucoinsShop);
        Item item = new Item();
        item.createItemInventory(label_item1, label_item1Name, label_item1Amount, game.redBull);
        item.createItemInventory(label_item2, label_item2Name, label_item2Amount, game.duplo);
        item.createItemInventory(label_item3, label_item3Name, label_item3Amount, game.omniSenseAudio);
    }//GEN-LAST:event_enterShopMouseClicked

    private void jBut_17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBut_17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBut_17ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        CSVRead read = new CSVRead();
        try {
            read.readCSV();
        } catch (Exception ex) {
            Logger.getLogger(Sims_1.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sims_1().setVisible(true);
            }
        });
    }
    //private javax.swing.JLabel label_timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Navi;
    private javax.swing.JPanel Shop;
    private javax.swing.JPanel StudField;
    private javax.swing.JDialog buyCoins;
    private javax.swing.JLabel creditsShop;
    private javax.swing.JLabel enterShop;
    private javax.swing.JButton exit;
    private javax.swing.JPanel gamePlanning;
    private javax.swing.JPanel gamePlaying;
    private javax.swing.JButton jBut_1;
    private javax.swing.JButton jBut_10;
    private javax.swing.JButton jBut_11;
    private javax.swing.JButton jBut_12;
    private javax.swing.JButton jBut_13;
    private javax.swing.JButton jBut_14;
    private javax.swing.JButton jBut_15;
    private javax.swing.JButton jBut_16;
    private javax.swing.JButton jBut_17;
    private javax.swing.JButton jBut_18;
    private javax.swing.JButton jBut_19;
    private javax.swing.JButton jBut_2;
    private javax.swing.JButton jBut_20;
    private javax.swing.JButton jBut_21;
    private javax.swing.JButton jBut_22;
    private javax.swing.JButton jBut_23;
    private javax.swing.JButton jBut_24;
    private javax.swing.JButton jBut_25;
    private javax.swing.JButton jBut_26;
    private javax.swing.JButton jBut_27;
    private javax.swing.JButton jBut_28;
    private javax.swing.JButton jBut_29;
    private javax.swing.JButton jBut_3;
    private javax.swing.JButton jBut_30;
    private javax.swing.JButton jBut_4;
    private javax.swing.JButton jBut_5;
    private javax.swing.JButton jBut_6;
    private javax.swing.JButton jBut_7;
    private javax.swing.JButton jBut_8;
    private javax.swing.JButton jBut_9;
    private javax.swing.JButton jBut_BackG;
    private javax.swing.JButton jBut_BackG2;
    private javax.swing.JButton jBut_ComboB_useItem;
    private javax.swing.JButton jBut_Dozent;
    private javax.swing.JButton jBut_Play;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboB_Items;
    private javax.swing.JLabel jLab_DozCounter;
    private javax.swing.JLabel jLab_DozSwitch;
    private javax.swing.JLabel jLab_Duplo;
    private javax.swing.JLabel jLab_Logo;
    private javax.swing.JLabel jLab_OMNI;
    private javax.swing.JLabel jLab_Redbull;
    private javax.swing.JLabel jLab_StudCounter;
    private javax.swing.JLabel jLab_StudSwitch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JPanel jPan_DozSwitch;
    private javax.swing.JPanel jPan_ItemSelect;
    private javax.swing.JPanel jPan_ItemStorage;
    private javax.swing.JPanel jPan_StudSwitch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgB_Motivation;
    private javax.swing.JProgressBar jProgB_Müdigkeit;
    private javax.swing.JProgressBar jProgB_Wissen;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel label_cheatSheetAmount;
    private javax.swing.JLabel label_cheatSheetLocked;
    private javax.swing.JLabel label_cheatSheetName;
    private javax.swing.JLabel label_duploAmount;
    private javax.swing.JLabel label_duploName;
    private javax.swing.JLabel label_item1;
    private javax.swing.JLabel label_item1Amount;
    private javax.swing.JLabel label_item1Name;
    private javax.swing.JLabel label_item2;
    private javax.swing.JLabel label_item2Amount;
    private javax.swing.JLabel label_item2Name;
    private javax.swing.JLabel label_item3;
    private javax.swing.JLabel label_item3Amount;
    private javax.swing.JLabel label_item3Name;
    private javax.swing.JLabel label_omniAmount;
    private javax.swing.JLabel label_omniLocked;
    private javax.swing.JLabel label_omniName;
    private javax.swing.JLabel label_redBullAmount;
    private javax.swing.JLabel label_redBullLocked;
    private javax.swing.JLabel label_redBullName;
    private javax.swing.JLabel label_redDuplolLocked;
    private javax.swing.JLabel label_timer;
    private javax.swing.JButton loadGame;
    private javax.swing.JPanel panel_cheatSheet;
    private javax.swing.JPanel panel_duplo;
    private javax.swing.JPanel panel_redBull;
    private javax.swing.JLabel punkteShop;
    private javax.swing.JPanel shop;
    private javax.swing.JButton startNewGame;
    private javax.swing.JPanel startPlanningGame;
    private javax.swing.JLabel ucoinsShop;
    // End of variables declaration//GEN-END:variables
}
