/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Stazzer
 */
public class Sims_1 extends javax.swing.JFrame {

    /**
     * Creates new form Sims
     */
    public CardLayout cl;
    public Game game;
    
    public Sims_1() {
        initComponents();
        setSize(1000, 700);
        buyCoins.setSize(400, 320);
        buyCoins.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jPanel2.setVisible(false);
        cl = (CardLayout)(jPanel2.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyCoins = new javax.swing.JDialog();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        startPlanningGame = new javax.swing.JPanel();
        startNewGame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        loadGame = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        gamePlanning = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jProgressBar7 = new javax.swing.JProgressBar();
        jProgressBar8 = new javax.swing.JProgressBar();
        jProgressBar10 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        Shop = new javax.swing.JPanel();
        enterShop = new javax.swing.JLabel();
        StudField = new javax.swing.JPanel();
        Navi = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jLabel90 = new javax.swing.JLabel();
        jLabel92 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel89 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel31 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel32 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        shop = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        label_item3 = new javax.swing.JLabel();
        label_item1 = new javax.swing.JLabel();
        label_item2 = new javax.swing.JLabel();
        label_item1Name = new javax.swing.JLabel();
        label_item1Amount = new javax.swing.JLabel();
        label_item2Name = new javax.swing.JLabel();
        label_item2Amount = new javax.swing.JLabel();
        label_item3Name = new javax.swing.JLabel();
        label_item3Amount = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        ucoinsShop = new javax.swing.JLabel();
        creditsShop = new javax.swing.JLabel();
        punkteShop = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        label_redBullOverlay = new javax.swing.JLabel();
        label_cheatSheetOverlay = new javax.swing.JLabel();
        label_omniOverlay = new javax.swing.JLabel();
        label_duploOverlay = new javax.swing.JLabel();
        panel_redBull = new javax.swing.JPanel();
        label_redBullName = new javax.swing.JLabel();
        label_redBullAmount = new javax.swing.JLabel();
        label_redBullLocked = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        label_omniName = new javax.swing.JLabel();
        label_omniLocked = new javax.swing.JLabel();
        label_omniAmount = new javax.swing.JLabel();
        panel_duplo = new javax.swing.JPanel();
        label_duploName = new javax.swing.JLabel();
        label_duploAmount = new javax.swing.JLabel();
        label_duploLocked = new javax.swing.JLabel();
        panel_cheatSheet = new javax.swing.JPanel();
        label_cheatSheetName = new javax.swing.JLabel();
        label_cheatSheetLocked = new javax.swing.JLabel();
        label_cheatSheetAmount = new javax.swing.JLabel();
        gamePlaying = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jProgressBar4 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jProgressBar6 = new javax.swing.JProgressBar();
        jPanel6 = new javax.swing.JPanel();
        label_timer = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        buyCoins.getContentPane().setLayout(null);

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel74.setText("UCoins => Credits Tausch");
        buyCoins.getContentPane().add(jLabel74);
        jLabel74.setBounds(30, 20, 370, 60);

        jLabel75.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel75.setText("UCoins:");
        buyCoins.getContentPane().add(jLabel75);
        jLabel75.setBounds(230, 110, 80, 20);

        jLabel76.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel76.setText("5 x");
        buyCoins.getContentPane().add(jLabel76);
        jLabel76.setBounds(300, 100, 80, 40);

        jLabel77.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel77.setText("Credits:");
        buyCoins.getContentPane().add(jLabel77);
        jLabel77.setBounds(50, 110, 70, 20);

        jLabel78.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel78.setText("600 x");
        buyCoins.getContentPane().add(jLabel78);
        jLabel78.setBounds(120, 100, 80, 40);

        jLabel79.setText("1 UCoin = 1000 Credits");
        buyCoins.getContentPane().add(jLabel79);
        jLabel79.setBounds(140, 150, 140, 30);

        jTextField1.setMinimumSize(new java.awt.Dimension(30, 20));
        buyCoins.getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 150, 40, 30);

        jButton2.setText("Tauschen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        buyCoins.getContentPane().add(jButton2);
        jButton2.setBounds(50, 220, 130, 23);

        jButton3.setText("Abbrechen");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        buyCoins.getContentPane().add(jButton3);
        jButton3.setBounds(210, 220, 130, 23);

        jTextField2.setMinimumSize(new java.awt.Dimension(30, 20));
        buyCoins.getContentPane().add(jTextField2);
        jTextField2.setBounds(80, 150, 40, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setMinimumSize(new java.awt.Dimension(1024, 786));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startPlanningGame.setMinimumSize(new java.awt.Dimension(800, 600));
        startPlanningGame.setName("");
        startPlanningGame.setPreferredSize(new java.awt.Dimension(800, 600));
        startPlanningGame.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startNewGame.setText("Neues Spiel");
        startNewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameActionPerformed(evt);
            }
        });
        startPlanningGame.add(startNewGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 160, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SIMS Test Menü");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startPlanningGame.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 330, 80));

        exit.setText("Beenden");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        startPlanningGame.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 160, 30));

        loadGame.setText("Spiel Laden");
        loadGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadGameActionPerformed(evt);
            }
        });
        startPlanningGame.add(loadGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 160, 30));

        jButton6.setText("Credits");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 160, 30));

        jButton7.setText("Profil");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 160, 30));

        jButton8.setText("Abmelden");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 160, 30));

        jButton13.setText("Statistik");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        startPlanningGame.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 160, 30));

        jPanel1.add(startPlanningGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        jPanel2.setLayout(new java.awt.CardLayout());

        gamePlanning.setName("card3");
        gamePlanning.setLayout(null);

        Logo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Logo.setLayout(null);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("SIMS Logo");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        Logo.add(jLabel27);
        jLabel27.setBounds(0, 0, 150, 110);

        gamePlanning.add(Logo);
        Logo.setBounds(0, 0, 150, 110);

        Header.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Header.setLayout(null);

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Wissen:");
        Header.add(jLabel41);
        jLabel41.setBounds(10, 10, 70, 20);

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Motivation:");
        Header.add(jLabel42);
        jLabel42.setBounds(10, 40, 80, 30);

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Müdigkeit:");
        Header.add(jLabel43);
        jLabel43.setBounds(10, 80, 90, 20);
        Header.add(jProgressBar7);
        jProgressBar7.setBounds(90, 80, 260, 20);
        Header.add(jProgressBar8);
        jProgressBar8.setBounds(90, 40, 260, 30);
        Header.add(jProgressBar10);
        jProgressBar10.setBounds(90, 10, 260, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("PLANUNGSPHASE");
        Header.add(jLabel3);
        jLabel3.setBounds(360, 10, 340, 90);

        gamePlanning.add(Header);
        Header.setBounds(150, 0, 700, 110);

        Shop.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Shop.setLayout(null);

        enterShop.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        enterShop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        enterShop.setText("SHOP");
        enterShop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterShopMouseClicked(evt);
            }
        });
        Shop.add(enterShop);
        enterShop.setBounds(0, 0, 130, 110);

        gamePlanning.add(Shop);
        Shop.setBounds(850, 0, 130, 110);

        StudField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        StudField.setLayout(null);
        gamePlanning.add(StudField);
        StudField.setBounds(150, 110, 830, 550);

        Navi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Navi.setLayout(null);

        jPanel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel28.setLayout(null);

        jLabel90.setText("Studenten umsetzen");
        jPanel28.add(jLabel90);
        jLabel90.setBounds(20, 30, 150, 20);

        jLabel92.setText("5 x");
        jPanel28.add(jLabel92);
        jLabel92.setBounds(60, 60, 60, 20);

        Navi.add(jPanel28);
        jPanel28.setBounds(0, 0, 150, 110);
        jPanel28.getAccessibleContext().setAccessibleDescription("");

        jPanel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel29.setLayout(null);

        jLabel89.setText("Dozenten tauschen");
        jPanel29.add(jLabel89);
        jLabel89.setBounds(20, 30, 110, 20);

        jLabel91.setText("1 x");
        jPanel29.add(jLabel91);
        jLabel91.setBounds(60, 60, 60, 20);

        Navi.add(jPanel29);
        jPanel29.setBounds(0, 110, 150, 110);

        jPanel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel30.setLayout(null);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item auswählen", "Spicker" }));
        jPanel30.add(jComboBox2);
        jComboBox2.setBounds(10, 40, 130, 20);

        Navi.add(jPanel30);
        jPanel30.setBounds(0, 220, 150, 110);

        jPanel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel31.setLayout(null);

        jLabel8.setText("Item-Vorräte");
        jPanel31.add(jLabel8);
        jLabel8.setBounds(10, 10, 80, 20);

        jLabel16.setText("Duplo: 3");
        jPanel31.add(jLabel16);
        jLabel16.setBounds(10, 50, 90, 14);

        jLabel44.setText("Redbull: 5");
        jPanel31.add(jLabel44);
        jLabel44.setBounds(10, 40, 90, 14);

        jLabel45.setText("Zum Shop Gehen!");
        jPanel31.add(jLabel45);
        jLabel45.setBounds(30, 90, 120, 14);

        Navi.add(jPanel31);
        jPanel31.setBounds(0, 330, 150, 110);

        jPanel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel32.setLayout(null);

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel46.setText("SPIELEN");
        jPanel32.add(jLabel46);
        jLabel46.setBounds(20, 30, 170, 50);

        Navi.add(jPanel32);
        jPanel32.setBounds(0, 440, 150, 110);

        gamePlanning.add(Navi);
        Navi.setBounds(0, 110, 150, 550);

        jPanel2.add(gamePlanning, "card3");

        shop.setLayout(null);

        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(null);

        jLabel55.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel55.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel55.setText("SIMS Logo");
        jLabel55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel55MouseClicked(evt);
            }
        });
        jPanel18.add(jLabel55);
        jLabel55.setBounds(0, 0, 150, 110);

        shop.add(jPanel18);
        jPanel18.setBounds(0, 0, 150, 110);

        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(null);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel56.setText("Inventar");
        jPanel19.add(jLabel56);
        jLabel56.setBounds(30, 0, 120, 40);

        jLabel58.setText("Studenten:");
        jPanel19.add(jLabel58);
        jLabel58.setBounds(10, 450, 80, 14);

        jLabel59.setText("4 / 40");
        jPanel19.add(jLabel59);
        jLabel59.setBounds(80, 450, 50, 14);

        jLabel60.setText("Semester: ");
        jPanel19.add(jLabel60);
        jLabel60.setBounds(10, 470, 80, 14);

        jLabel61.setText("3 / 6");
        jPanel19.add(jLabel61);
        jLabel61.setBounds(80, 470, 60, 14);

        label_item3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(label_item3);
        label_item3.setBounds(30, 250, 90, 80);

        label_item1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.add(label_item1);
        label_item1.setBounds(30, 50, 90, 80);

        label_item2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_item2.setPreferredSize(new java.awt.Dimension(20, 20));
        jPanel19.add(label_item2);
        label_item2.setBounds(30, 150, 90, 80);

        label_item1Name.setText("jLabel4");
        jPanel19.add(label_item1Name);
        label_item1Name.setBounds(60, 80, 34, 14);

        label_item1Amount.setText("jLabel4");
        jPanel19.add(label_item1Amount);
        label_item1Amount.setBounds(60, 100, 34, 14);

        label_item2Name.setText("jLabel4");
        jPanel19.add(label_item2Name);
        label_item2Name.setBounds(60, 190, 34, 14);

        label_item2Amount.setText("jLabel4");
        jPanel19.add(label_item2Amount);
        label_item2Amount.setBounds(60, 210, 34, 14);

        label_item3Name.setText("jLabel4");
        jPanel19.add(label_item3Name);
        label_item3Name.setBounds(60, 280, 34, 14);

        label_item3Amount.setText("jLabel26");
        jPanel19.add(label_item3Amount);
        label_item3Amount.setBounds(60, 300, 40, 14);

        shop.add(jPanel19);
        jPanel19.setBounds(0, 110, 150, 550);

        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(null);

        ucoinsShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ucoinsShop.setText("0");
        jPanel20.add(ucoinsShop);
        ucoinsShop.setBounds(80, 10, 80, 20);

        creditsShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        creditsShop.setText("0");
        jPanel20.add(creditsShop);
        creditsShop.setBounds(80, 40, 70, 17);

        punkteShop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        punkteShop.setText("0");
        jPanel20.add(punkteShop);
        punkteShop.setBounds(80, 70, 70, 17);

        jButton12.setText("UCoins Tauschen");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel20.add(jButton12);
        jButton12.setBounds(230, 10, 160, 90);

        jLabel70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel70.setText("UCoins:");
        jPanel20.add(jLabel70);
        jLabel70.setBounds(10, 10, 80, 20);

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Credits:");
        jPanel20.add(jLabel71);
        jLabel71.setBounds(10, 40, 70, 17);

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("Punkte:");
        jPanel20.add(jLabel72);
        jLabel72.setBounds(10, 70, 70, 17);

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel85.setText("SHOP");
        jPanel20.add(jLabel85);
        jLabel85.setBounds(470, 0, 210, 110);

        shop.add(jPanel20);
        jPanel20.setBounds(150, 0, 700, 110);

        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(null);

        jLabel54.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel54.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel54.setText("SPIEL");
        jLabel54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel54MouseClicked(evt);
            }
        });
        jPanel21.add(jLabel54);
        jLabel54.setBounds(0, 0, 130, 110);

        shop.add(jPanel21);
        jPanel21.setBounds(850, 0, 130, 110);

        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(null);

        label_redBullOverlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_redBullOverlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_redBullOverlayMouseClicked(evt);
            }
        });
        jPanel22.add(label_redBullOverlay);
        label_redBullOverlay.setBounds(100, 40, 230, 220);

        label_cheatSheetOverlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_cheatSheetOverlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_cheatSheetOverlayMouseClicked(evt);
            }
        });
        jPanel22.add(label_cheatSheetOverlay);
        label_cheatSheetOverlay.setBounds(100, 300, 230, 220);

        label_omniOverlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_omniOverlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_omniOverlayMouseClicked(evt);
            }
        });
        jPanel22.add(label_omniOverlay);
        label_omniOverlay.setBounds(510, 300, 230, 220);

        label_duploOverlay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        label_duploOverlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_duploOverlayMouseClicked(evt);
            }
        });
        jPanel22.add(label_duploOverlay);
        label_duploOverlay.setBounds(510, 40, 230, 220);

        panel_redBull.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_redBull.setName("panel_redBull");
        panel_redBull.setLayout(null);

        label_redBullName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_redBullName.setText("Red Bull");
        panel_redBull.add(label_redBullName);
        label_redBullName.setBounds(0, 130, 230, 30);

        label_redBullAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_redBullAmount.setText("100 Credits");
        panel_redBull.add(label_redBullAmount);
        label_redBullAmount.setBounds(0, 150, 230, 50);

        label_redBullLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_redBullLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_redBullLocked.setText("GESPERRT");
        panel_redBull.add(label_redBullLocked);
        label_redBullLocked.setBounds(50, 10, 230, 110);

        jPanel22.add(panel_redBull);
        panel_redBull.setBounds(100, 40, 230, 220);

        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel23.setLayout(null);

        label_omniName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_omniName.setText("Verfügbar ab Semester 4");
        jPanel23.add(label_omniName);
        label_omniName.setBounds(0, 120, 230, 50);

        label_omniLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_omniLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_omniLocked.setText("GESPERRT");
        jPanel23.add(label_omniLocked);
        label_omniLocked.setBounds(50, 20, 230, 110);

        label_omniAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_omniAmount.setText("5 UCoins");
        jPanel23.add(label_omniAmount);
        label_omniAmount.setBounds(0, 150, 230, 50);

        jPanel22.add(jPanel23);
        jPanel23.setBounds(510, 300, 230, 220);

        panel_duplo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_duplo.setLayout(null);

        label_duploName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_duploName.setText("Duplo");
        panel_duplo.add(label_duploName);
        label_duploName.setBounds(0, 130, 230, 30);

        label_duploAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_duploAmount.setText("100 Credits");
        panel_duplo.add(label_duploAmount);
        label_duploAmount.setBounds(0, 150, 230, 50);

        label_duploLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_duploLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_duploLocked.setText("GESPERRT");
        panel_duplo.add(label_duploLocked);
        label_duploLocked.setBounds(50, 10, 230, 110);

        jPanel22.add(panel_duplo);
        panel_duplo.setBounds(510, 40, 230, 220);

        panel_cheatSheet.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel_cheatSheet.setLayout(null);

        label_cheatSheetName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_cheatSheetName.setText("Spicker");
        panel_cheatSheet.add(label_cheatSheetName);
        label_cheatSheetName.setBounds(0, 130, 230, 30);

        label_cheatSheetLocked.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label_cheatSheetLocked.setForeground(new java.awt.Color(204, 51, 0));
        label_cheatSheetLocked.setText("GESPERRT");
        panel_cheatSheet.add(label_cheatSheetLocked);
        label_cheatSheetLocked.setBounds(50, 10, 230, 110);

        label_cheatSheetAmount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label_cheatSheetAmount.setText("5 UCoins");
        panel_cheatSheet.add(label_cheatSheetAmount);
        label_cheatSheetAmount.setBounds(0, 150, 230, 50);

        jPanel22.add(panel_cheatSheet);
        panel_cheatSheet.setBounds(100, 300, 230, 220);

        shop.add(jPanel22);
        jPanel22.setBounds(150, 110, 830, 550);

        jPanel2.add(shop, "card4");

        gamePlaying.setMinimumSize(new java.awt.Dimension(1024, 768));
        gamePlaying.setPreferredSize(new java.awt.Dimension(1024, 768));
        gamePlaying.setLayout(null);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SIMS Logo");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 150, 110);

        gamePlaying.add(jPanel3);
        jPanel3.setBounds(0, 0, 150, 110);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Inventar");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(30, 0, 120, 40);

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(30, 250, 90, 80);

        jLabel18.setText("Studenten:");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(10, 420, 80, 14);

        jLabel19.setText("4 / 40");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(80, 420, 50, 14);

        jLabel20.setText("Semester: ");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(10, 440, 80, 14);

        jLabel21.setText("3 / 6");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(80, 440, 60, 14);

        jLabel22.setText("UCoins: 300");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(80, 350, 80, 14);

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel17);
        jLabel17.setBounds(30, 150, 90, 80);

        jLabel23.setText("Credis: 700");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(10, 350, 70, 14);

        jLabel24.setText("Red Bull");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(50, 160, 90, 30);

        jLabel25.setText("3 x");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(60, 190, 40, 14);

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.add(jLabel15);
        jLabel15.setBounds(30, 50, 90, 80);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Punkte:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(10, 480, 70, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("700");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(90, 470, 40, 40);

        gamePlaying.add(jPanel4);
        jPanel4.setBounds(0, 110, 150, 550);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Wissen:");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 10, 70, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Motivation:");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(10, 30, 80, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Müdigkeit:");
        jPanel5.add(jLabel7);
        jLabel7.setBounds(10, 80, 80, 20);
        jPanel5.add(jProgressBar1);
        jProgressBar1.setBounds(80, 10, 260, 20);
        jPanel5.add(jProgressBar2);
        jProgressBar2.setBounds(80, 40, 260, 20);
        jPanel5.add(jProgressBar4);
        jProgressBar4.setBounds(80, 80, 260, 20);

        jButton1.setText("Fenster : AUF");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);
        jButton1.setBounds(350, 10, 120, 23);

        jButton4.setText("Gruppenarbeit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);
        jButton4.setBounds(350, 40, 120, 23);

        jButton5.setText("Pause");
        jPanel5.add(jButton5);
        jButton5.setBounds(350, 80, 120, 23);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Lärmpegel:");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(480, 10, 80, 20);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Luftqualität:");
        jPanel5.add(jLabel10);
        jLabel10.setBounds(480, 34, 80, 30);
        jPanel5.add(jProgressBar5);
        jProgressBar5.setBounds(560, 10, 130, 20);
        jPanel5.add(jProgressBar6);
        jProgressBar6.setBounds(560, 40, 130, 20);

        gamePlaying.add(jPanel5);
        jPanel5.setBounds(150, 0, 700, 110);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        label_timer.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        label_timer.setText("--:--");
        jPanel6.add(label_timer);
        label_timer.setBounds(10, 10, 140, 90);

        gamePlaying.add(jPanel6);
        jPanel6.setBounds(850, 0, 130, 110);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        gamePlaying.add(jPanel7);
        jPanel7.setBounds(150, 110, 830, 550);

        jPanel2.add(gamePlaying, "card2");

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void startNewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameActionPerformed
        // TODO add your handling code here:
        if(jPanel2.isVisible() == false){
            jPanel2.setVisible(true);
        }    
        cl.show(jPanel2, "card2");
        startPlanningGame.setVisible(false);
        ActivityPhase phase = new ActivityPhase(label_timer); // added by Jörg
    }//GEN-LAST:event_startNewGameActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void loadGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadGameActionPerformed
        // TODO add your handling code here:
        if(jPanel2.isVisible() == false){
            jPanel2.setVisible(true);
        }    
        cl.show(jPanel2, "card3");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_loadGameActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        buyCoins.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void enterShopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterShopMouseClicked
        // TODO add your handling code here:
        cl.show(jPanel2, "card4");
        startPlanningGame.setVisible(false);
        OpenShop labels = new OpenShop();
        labels.changeLabels(creditsShop, punkteShop, ucoinsShop);
        Item item = new Item();
        item.createItemInventory(label_item1,label_item1Name,label_item1Amount, game.redBull);
        item.createItemInventory(label_item2,label_item2Name,label_item2Amount, game.duplo);
        item.createItemInventory(label_item3,label_item3Name,label_item3Amount, game.omniSenseAudio);
        item.createItemShop(label_redBullName, label_redBullAmount, label_redBullLocked, game.redBull);
        item.createItemShop(label_duploName, label_duploAmount, label_duploLocked, game.duplo);
        item.createItemShop(label_cheatSheetName, label_cheatSheetAmount, label_cheatSheetLocked, game.cheatSheet);
        item.createItemShop(label_omniName, label_omniAmount, label_omniLocked, game.omniSenseAudio);
    }//GEN-LAST:event_enterShopMouseClicked

    private void jLabel55MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel55MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel55MouseClicked

    private void jLabel54MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel54MouseClicked
        // TODO add your handling code here:
        cl.show(jPanel2, "card3");
        startPlanningGame.setVisible(false);
    }//GEN-LAST:event_jLabel54MouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        buyCoins.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        jPanel2.setVisible(false);
        startPlanningGame.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       String test = jButton1.getText();
       if(test.equals("Fenster : AUF")){
           jButton1.setText("Fenster : ZU");
       }
       if(test.equals("Fenster : ZU")){
           jButton1.setText("Fenster : AUF");
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void label_redBullOverlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_redBullOverlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_redBullOverlayMouseClicked

    private void label_duploOverlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_duploOverlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_duploOverlayMouseClicked

    private void label_cheatSheetOverlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_cheatSheetOverlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_cheatSheetOverlayMouseClicked

    private void label_omniOverlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_omniOverlayMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_label_omniOverlayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sims.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        CSVRead read = new CSVRead();
        try {
            read.readCSV();
        } catch (Exception ex) {
            Logger.getLogger(Sims_1.class.getName()).log(Level.SEVERE, null, ex);
        }

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Sims_1().setVisible(true);
            }
        });
    }
    //private javax.swing.JLabel label_timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel Navi;
    private javax.swing.JPanel Shop;
    private javax.swing.JPanel StudField;
    private javax.swing.JDialog buyCoins;
    private javax.swing.JLabel creditsShop;
    private javax.swing.JLabel enterShop;
    private javax.swing.JButton exit;
    private javax.swing.JPanel gamePlanning;
    private javax.swing.JPanel gamePlaying;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar10;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    private javax.swing.JProgressBar jProgressBar7;
    private javax.swing.JProgressBar jProgressBar8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel label_cheatSheetAmount;
    private javax.swing.JLabel label_cheatSheetLocked;
    private javax.swing.JLabel label_cheatSheetName;
    private javax.swing.JLabel label_cheatSheetOverlay;
    private javax.swing.JLabel label_duploAmount;
    private javax.swing.JLabel label_duploLocked;
    private javax.swing.JLabel label_duploName;
    private javax.swing.JLabel label_duploOverlay;
    private javax.swing.JLabel label_item1;
    private javax.swing.JLabel label_item1Amount;
    private javax.swing.JLabel label_item1Name;
    private javax.swing.JLabel label_item2;
    private javax.swing.JLabel label_item2Amount;
    private javax.swing.JLabel label_item2Name;
    private javax.swing.JLabel label_item3;
    private javax.swing.JLabel label_item3Amount;
    private javax.swing.JLabel label_item3Name;
    private javax.swing.JLabel label_omniAmount;
    private javax.swing.JLabel label_omniLocked;
    private javax.swing.JLabel label_omniName;
    private javax.swing.JLabel label_omniOverlay;
    private javax.swing.JLabel label_redBullAmount;
    private javax.swing.JLabel label_redBullLocked;
    private javax.swing.JLabel label_redBullName;
    private javax.swing.JLabel label_redBullOverlay;
    private javax.swing.JLabel label_timer;
    private javax.swing.JButton loadGame;
    private javax.swing.JPanel panel_cheatSheet;
    private javax.swing.JPanel panel_duplo;
    private javax.swing.JPanel panel_redBull;
    private javax.swing.JLabel punkteShop;
    private javax.swing.JPanel shop;
    private javax.swing.JButton startNewGame;
    private javax.swing.JPanel startPlanningGame;
    private javax.swing.JLabel ucoinsShop;
    // End of variables declaration//GEN-END:variables
}
